[build]
  publish = "."
  functions = "netlify/functions"

[[redirects]]
  from = "/api/ac-sync"
  to = "/.netlify/functions/ac-sync"
  status = 200

[[redirects]]
  from = "/api/lc-sync"
  to = "/.netlify/functions/lc-sync"
  status = 200

[[redirects]]
  from = "/api/contests-proxy"
  to = "/.netlify/functions/contests-proxy"
  status = 200